use Workout;
GRANT DROP,SELECT, INSERT, UPDATE, CREATE TEMPORARY TABLES, LOCK TABLES  ON Workout.* TO 'root'@'%';
GRANT SELECT, INSERT, UPDATE, CREATE TEMPORARY TABLES, LOCK TABLES ON Workout.* TO 'IUSER_Workout'@'localhost';

